"""
反馈组装 Agent，负责把最终裁决结果整理成稳定的用户反馈结构。

Feedback Assembler — unified feedback output for deterministic and real runs.

This is the canonical feedback entrypoint for the pipeline. It always returns
the same top-level structure and the same per-dimension fields, regardless of
whether commentary text is rendered deterministically or generated by a real
LLM provider.

Canonical output schema (Dict[str, Any]):
  {
    "dimensions": {
      "<dimension_id>": {
        "dimension_name": str,
        "canonical_score": int,
        "final_score": int,              # backward-compatible alias
        "display_score": str,
        "display_annotation": str | None,
        "descriptor_refs": List[str],
        "evidence_span_ids": List[str],
        "evidence_count": int,
        "feedback_text": str,
        "commentary": str,               # same value as feedback_text
        "uncertainty_note": str | None,
        "decision_confidence": float,
        "confidence": float,             # backward-compatible alias
        "rationale": str,                # backward-compatible alias
        "scorer_rationale": str,         # scorer justification passthrough
        "was_adjudicated": bool,
      },
      ...
    },
    "violations": List[Dict[str, str]],
    "generated_at": str,
    "summary": str,
    "provider": str,
  }
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

from src.agents.prompt_builders import build_explanation_prompt
from src.contracts.artifact_bundle import PolicySnapshot, RubricSnapshot
from src.contracts.evidence import (
    DimensionObservation,
    EvidenceSpan,
    ObservationConfidence,
)
from src.contracts.scoring import FinalDimensionDecision, ScoreHypothesis
from src.policies.explanation import (
    enforce_explanation_policy,
    render_dimension_explanation,
)
from src.providers.base import BaseProvider, LLMRequest
from src.providers.prompt_loader import PromptTemplate


def _max_commentary_length(policy: PolicySnapshot) -> int:
    constraints = policy.explanation_policy.get("output_constraints", {})
    return int(constraints.get("max_commentary_length_per_dimension", 500))


def _render_commentary(
    decision: FinalDimensionDecision,
    observation: DimensionObservation,
    decision_spans: List[EvidenceSpan],
    rubric: RubricSnapshot,
    provider: Optional[BaseProvider],
    template: Optional[PromptTemplate],
    fallback_text: str,
    max_length: int,
    scorer_rationale: Optional[str] = None,
    override_template: Optional[PromptTemplate] = None,
) -> str:
    """Render commentary either deterministically or via a real provider."""
    if provider is None and template is None:
        return fallback_text
    if provider is None or template is None:
        raise ValueError("feedback.run() requires both provider and template together")

    template_used = override_template or template
    prompt_text = build_explanation_prompt(
        decision=decision,
        observation=observation,
        evidence_spans=decision_spans,
        rubric=rubric,
        template=template,
        scorer_rationale=scorer_rationale,
        override_template=override_template,
    )
    response = provider.complete(
        LLMRequest(
            prompt=prompt_text,
            metadata={
                "node_id": "node_feedback",
                "stage_name": "feedback",
                "dimension_id": decision.dimension_id,
                "decision_id": decision.decision_id,
                "template_source": template_used.source_path,
                "template_version": template_used.metadata.get("template_version"),
                "used_override_template": override_template is not None,
                "evidence_span_count": len(decision_spans),
            },
        )
    )
    text = response.content.strip()
    if not text:
        return fallback_text
    return text[:max_length]


def _fallback_observation(decision: FinalDimensionDecision) -> DimensionObservation:
    """Build a minimal observation when no observation is available for a dimension."""
    return DimensionObservation(
        observation_id=f"obs-feedback-fallback-{decision.dimension_id}",
        document_id="unknown",
        dimension_id=decision.dimension_id,
        supporting_span_ids=list(decision.evidence_span_ids),
        counter_span_ids=[],
        facet_findings=[],
        observation_confidence=ObservationConfidence.MEDIUM,
        uncertainty_notes=[],
    )


def _find_primary_hypothesis(
    decision: FinalDimensionDecision,
    hyp_by_id: Dict[str, ScoreHypothesis],
    hyps_by_dim: Dict[str, List[ScoreHypothesis]],
) -> Optional[ScoreHypothesis]:
    """Find the scorer hypothesis that best matches a final decision."""
    primary = hyp_by_id.get(decision.primary_hypothesis_id)
    if primary is not None:
        return primary
    dim_hyps = hyps_by_dim.get(decision.dimension_id, [])
    if not dim_hyps:
        return None
    return sorted(dim_hyps, key=lambda h: (h.rater_id, h.hypothesis_id))[0]


def run(
    decisions: List[FinalDimensionDecision],
    observations: List[DimensionObservation],
    spans: List[EvidenceSpan],
    hypotheses: Optional[List[ScoreHypothesis]] = None,
    rubric: Optional[RubricSnapshot] = None,
    policy: Optional[PolicySnapshot] = None,
    provider: Optional[BaseProvider] = None,
    template: Optional[PromptTemplate] = None,
    override_templates: Optional[Dict[str, PromptTemplate]] = None,
) -> Dict[str, Any]:
    """Assemble a unified feedback dict from final scoring decisions.

    Args:
        decisions: FinalDimensionDecision objects (one per dimension).
        observations: DimensionObservation objects for optional evidence counts.
        spans: EvidenceSpan objects for commentary and citation rendering.
        hypotheses: Optional ScoreHypothesis objects for scorer rationale lookup.
        rubric: RubricSnapshot for dimension metadata.
        policy: PolicySnapshot containing explanation policy config.
        provider: Optional real provider used to generate commentary text.
        template: Optional explanation prompt template paired with provider.
        override_templates: Optional per-dimension explanation override templates.

    Returns:
        Unified feedback dict with stable keys across deterministic and real runs.
    """
    # Backward compatibility:
    # legacy calls use run(decisions, observations, spans, rubric, policy, ...)
    if (
        isinstance(hypotheses, RubricSnapshot)
        and isinstance(rubric, PolicySnapshot)
        and policy is None
    ):
        resolved_hypotheses: List[ScoreHypothesis] = []
        resolved_rubric = hypotheses
        resolved_policy = rubric
    else:
        if rubric is None or policy is None:
            raise ValueError("feedback.run() requires rubric and policy")
        resolved_hypotheses = list(hypotheses or [])
        resolved_rubric = rubric
        resolved_policy = policy

    span_by_id: Dict[str, EvidenceSpan] = {s.span_id: s for s in spans}
    obs_by_dim: Dict[str, DimensionObservation] = {
        obs.dimension_id: obs for obs in observations
    }
    hyp_by_id: Dict[str, ScoreHypothesis] = {
        hyp.hypothesis_id: hyp for hyp in resolved_hypotheses
    }
    hyps_by_dim: Dict[str, List[ScoreHypothesis]] = {}
    for hyp in resolved_hypotheses:
        hyps_by_dim.setdefault(hyp.dimension_id, []).append(hyp)

    max_length = _max_commentary_length(resolved_policy)
    overrides = override_templates or {}

    explanations = []
    dimensions_out: Dict[str, Any] = {}

    for decision in decisions:
        dim_id = decision.dimension_id
        obs = obs_by_dim.get(dim_id) or _fallback_observation(decision)
        selected_hyp = _find_primary_hypothesis(decision, hyp_by_id, hyps_by_dim)
        scorer_rationale = (
            (selected_hyp.rationale or "").strip() if selected_hyp is not None else ""
        )
        override_template = overrides.get(dim_id)

        decision_spans = [
            span_by_id[sid]
            for sid in decision.evidence_span_ids
            if sid in span_by_id
        ]

        explanation = render_dimension_explanation(
            decision=decision,
            spans=decision_spans,
            rubric=resolved_rubric,
            policy=resolved_policy,
            observation=obs,
            scorer_rationale=scorer_rationale or None,
        )
        feedback_text = _render_commentary(
            decision=decision,
            observation=obs,
            decision_spans=decision_spans,
            rubric=resolved_rubric,
            provider=provider,
            template=template,
            fallback_text=explanation.commentary,
            max_length=max_length,
            scorer_rationale=scorer_rationale or None,
            override_template=override_template,
        )

        explanations.append(explanation)

        evidence_count = len(decision.evidence_span_ids)
        evidence_count = max(evidence_count, len(obs.supporting_span_ids))

        dimensions_out[dim_id] = {
            "dimension_name": explanation.dimension_name,
            "canonical_score": explanation.canonical_score,
            "final_score": explanation.canonical_score,
            "display_score": explanation.display_score,
            "display_annotation": decision.final_score.display_annotation,
            "descriptor_refs": list(explanation.descriptor_refs),
            "evidence_span_ids": list(explanation.evidence_span_ids),
            "evidence_count": evidence_count,
            "feedback_text": feedback_text,
            "commentary": feedback_text,
            "uncertainty_note": explanation.uncertainty_note,
            "decision_confidence": decision.decision_confidence,
            "confidence": decision.decision_confidence,
            "rationale": decision.decision_note or "",
            "scorer_rationale": scorer_rationale,
            "was_adjudicated": decision.adjudication_id is not None,
        }

    violations = enforce_explanation_policy(explanations, resolved_policy)
    provider_name = provider.name if provider is not None else "mock"
    mode_label = "LLM-generated" if provider is not None else "deterministic"

    return {
        "dimensions": dimensions_out,
        "violations": [
            {
                "dimension_id": violation.dimension_id,
                "violation_type": violation.violation_type,
                "detail": violation.detail,
            }
            for violation in violations
        ],
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "summary": f"{mode_label} feedback for {len(decisions)} dimension(s).",
        "provider": provider_name,
    }
