"""
Feedback Assembler — unified feedback output for deterministic and real runs.

This is the canonical feedback entrypoint for the pipeline. It always returns
the same top-level structure and the same per-dimension fields, regardless of
whether commentary text is rendered deterministically or generated by a real
LLM provider.

Canonical output schema (Dict[str, Any]):
  {
    "dimensions": {
      "<dimension_id>": {
        "dimension_name": str,
        "canonical_score": int,
        "final_score": int,              # backward-compatible alias
        "display_score": str,
        "display_annotation": str | None,
        "descriptor_refs": List[str],
        "evidence_span_ids": List[str],
        "evidence_count": int,
        "feedback_text": str,
        "commentary": str,               # same value as feedback_text
        "uncertainty_note": str | None,
        "decision_confidence": float,
        "confidence": float,             # backward-compatible alias
        "rationale": str,                # backward-compatible alias
      },
      ...
    },
    "violations": List[Dict[str, str]],
    "generated_at": str,
    "summary": str,
    "provider": str,
  }
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

from src.agents.prompt_builders import build_explanation_prompt
from src.contracts.artifact_bundle import PolicySnapshot, RubricSnapshot
from src.contracts.evidence import DimensionObservation, EvidenceSpan
from src.contracts.scoring import FinalDimensionDecision
from src.policies.explanation import (
    enforce_explanation_policy,
    render_dimension_explanation,
)
from src.providers.base import BaseProvider, LLMRequest
from src.providers.prompt_loader import PromptTemplate


def _max_commentary_length(policy: PolicySnapshot) -> int:
    constraints = policy.explanation_policy.get("output_constraints", {})
    return int(constraints.get("max_commentary_length_per_dimension", 500))


def _render_commentary(
    decision: FinalDimensionDecision,
    decision_spans: List[EvidenceSpan],
    rubric: RubricSnapshot,
    provider: Optional[BaseProvider],
    template: Optional[PromptTemplate],
    fallback_text: str,
    max_length: int,
) -> str:
    """Render commentary either deterministically or via a real provider."""
    if provider is None and template is None:
        return fallback_text
    if provider is None or template is None:
        raise ValueError("feedback.run() requires both provider and template together")

    prompt_text = build_explanation_prompt(decision, decision_spans, rubric, template)
    response = provider.complete(LLMRequest(prompt=prompt_text))
    text = response.content.strip()
    if not text:
        return fallback_text
    return text[:max_length]


def run(
    decisions: List[FinalDimensionDecision],
    observations: List[DimensionObservation],
    spans: List[EvidenceSpan],
    rubric: RubricSnapshot,
    policy: PolicySnapshot,
    provider: Optional[BaseProvider] = None,
    template: Optional[PromptTemplate] = None,
) -> Dict[str, Any]:
    """Assemble a unified feedback dict from final scoring decisions.

    Args:
        decisions: FinalDimensionDecision objects (one per dimension).
        observations: DimensionObservation objects for optional evidence counts.
        spans: EvidenceSpan objects for commentary and citation rendering.
        rubric: RubricSnapshot for dimension metadata.
        policy: PolicySnapshot containing explanation policy config.
        provider: Optional real provider used to generate commentary text.
        template: Optional explanation prompt template paired with provider.

    Returns:
        Unified feedback dict with stable keys across deterministic and real runs.
    """
    span_by_id: Dict[str, EvidenceSpan] = {s.span_id: s for s in spans}
    obs_by_dim: Dict[str, DimensionObservation] = {
        obs.dimension_id: obs for obs in observations
    }
    max_length = _max_commentary_length(policy)

    explanations = []
    dimensions_out: Dict[str, Any] = {}

    for decision in decisions:
        dim_id = decision.dimension_id
        obs = obs_by_dim.get(dim_id)
        decision_spans = [
            span_by_id[sid]
            for sid in decision.evidence_span_ids
            if sid in span_by_id
        ]

        explanation = render_dimension_explanation(decision, spans, rubric, policy)
        feedback_text = _render_commentary(
            decision=decision,
            decision_spans=decision_spans,
            rubric=rubric,
            provider=provider,
            template=template,
            fallback_text=explanation.commentary,
            max_length=max_length,
        )

        explanations.append(explanation)

        evidence_count = len(decision.evidence_span_ids)
        if obs is not None:
            evidence_count = max(evidence_count, len(obs.supporting_span_ids))

        dimensions_out[dim_id] = {
            "dimension_name": explanation.dimension_name,
            "canonical_score": explanation.canonical_score,
            "final_score": explanation.canonical_score,
            "display_score": explanation.display_score,
            "display_annotation": decision.final_score.display_annotation,
            "descriptor_refs": list(explanation.descriptor_refs),
            "evidence_span_ids": list(explanation.evidence_span_ids),
            "evidence_count": evidence_count,
            "feedback_text": feedback_text,
            "commentary": feedback_text,
            "uncertainty_note": explanation.uncertainty_note,
            "decision_confidence": decision.decision_confidence,
            "confidence": decision.decision_confidence,
            "rationale": decision.decision_note or "",
        }

    violations = enforce_explanation_policy(explanations, policy)
    provider_name = provider.name if provider is not None else "mock"
    mode_label = "LLM-generated" if provider is not None else "deterministic"

    return {
        "dimensions": dimensions_out,
        "violations": [
            {
                "dimension_id": violation.dimension_id,
                "violation_type": violation.violation_type,
                "detail": violation.detail,
            }
            for violation in violations
        ],
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "summary": f"{mode_label} feedback for {len(decisions)} dimension(s).",
        "provider": provider_name,
    }
